services:
  - type: web
    name: task-project
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node src/index.js
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 20
